### ISSUE TITLE
CI meta

### ISSUE THREAD

**Issue by neic** [neic/pyguitest#1]
- [x] auto build on commit
- [x] black
- [x] test
- [ ] code coverage
- [ ] snyk
- [ ] package
- [ ] push to pypi
- [x] `pyinstaller`
  - [x] linux
  - [ ] macOS
  - [ ] Windows
- [ ] Release on github
- [ ] test binary
  - [ ] linux
  - [ ] macOS
  - [ ] Windows
- [ ] Report on github PR
- [ ] badge
